language: java
sudo: required

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.6 mongodb-org-server=3.0.6 mongodb-org-shell=3.0.6 mongodb-org-mongos=3.0.6 mongodb-org-tools=3.0.6
  - sudo service mongodb start
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongo --version
  - mongo testdb --eval 'db.createUser( { "user":"build","pwd":"test" } );'
  #import test json data here
  - mongo testdb ./opengridservice/src/test/resources/testdata.js

script:
  - mvn install -f ./opengridservice/pom.xml

notifications:
  email:
    on_success: change
    on_failure: change
